// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5m1UGVhFfmNVm7U7wPScSu_Lw9i9nqqI',
    appId: '1:161916040907:web:671ee991173b0db0ef0d4e',
    messagingSenderId: '161916040907',
    projectId: 'sjs-ess-9c531',
    authDomain: 'sjs-ess-9c531.firebaseapp.com',
    storageBucket: 'sjs-ess-9c531.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuF3mdslytXLpffOob4uJHUigDvVPawQ',
    appId: '1:161916040907:android:020acbede88b6276ef0d4e',
    messagingSenderId: '161916040907',
    projectId: 'sjs-ess-9c531',
    storageBucket: 'sjs-ess-9c531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHpkgw312WTDAO26h-AxZ7roUu-s5o1g',
    appId: '1:161916040907:ios:abb60d7f186dea33ef0d4e',
    messagingSenderId: '161916040907',
    projectId: 'sjs-ess-9c531',
    storageBucket: 'sjs-ess-9c531.firebasestorage.app',
    iosBundleId: 'com.nijatech.sjs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHpkgw312WTDAO26h-AxZ7roUu-s5o1g',
    appId: '1:161916040907:ios:abb60d7f186dea33ef0d4e',
    messagingSenderId: '161916040907',
    projectId: 'sjs-ess-9c531',
    storageBucket: 'sjs-ess-9c531.firebasestorage.app',
    iosBundleId: 'com.nijatech.sjs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5m1UGVhFfmNVm7U7wPScSu_Lw9i9nqqI',
    appId: '1:161916040907:web:ca80d2899931f550ef0d4e',
    messagingSenderId: '161916040907',
    projectId: 'sjs-ess-9c531',
    authDomain: 'sjs-ess-9c531.firebaseapp.com',
    storageBucket: 'sjs-ess-9c531.firebasestorage.app',
  );

}